### PR TITLE
wrong close tag

### PR DESCRIPTION
**Pull request by frunjik**
the tag of the custom element is wrong (confused me :))
[my frst github change ever ...]

### CODE REVIEW

**Comment by ebidel** [comment]
Before this PR can be merged, please sign the CLA. See the [CONTRIBUTING](http://polymer.github.io/CONTRIBUTORS.txt) guide.

**Comment by frunjik** [comment]
thx,
did

2014-07-22 0:13 GMT+02:00 Eric Bidelman notifications@github.com:

**Comment by ebidel** [comment]
Thanks for signing the CLA!

**Comment by frunjik** [comment]
Eric sorry to disturb you (and a late happy birthday).

Do i have to do something now ?
I was not aware that the whole thing would be cloned for one slash  - i
dont want to put u to work :)

I love polymer :)
But i am a bit lost in it and github :)
Can you tell me what is the best place to ask (newbie!!) questions ?
Thx

-J

2014-07-23 0:54 GMT+02:00 Eric Bidelman notifications@github.com:

**Comment by ebidel** [comment]
Thanks :) Just waiting for someone to review. This LGTM. Thanks for submitting it.

**Comment by sjmiles** [comment]
`core-layout` is deprecated.

**Comment by frunjik** [comment]
What is is replaced with ?

2014-07-23 19:57 GMT+02:00 Scott J. Miles notifications@github.com:

**Comment by ebidel** [comment]
The layout attributes and newer layout elements:

http://www.polymer-project.org/docs/polymer/layout-attrs.html
http://www.polymer-project.org/docs/elements/layout-elements.html

**Comment by frunjik** [comment]
Eric, sorry to disturb you again.
I did another miniscule commit, and i get the request to sign CLA again...
What do i need to not get that everytime ??
Thanx for your (precious time)

PewPolyPower!

2014-07-23 0:54 GMT+02:00 Eric Bidelman notifications@github.com:

**Comment by robdodson** [comment]
The CLA bot is a little crazy. If you've signed the CLA once and gotten the
'thanks for signing!' message then you should be all set

**Comment by ebidel** [comment]
Where was that commit?

**Pull request merged**
